version: '3.3'
services:
  db:
    container_name: ecommerce-database
    image: postgres:9.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
  backend:
    build: backend/.
    container_name: ecommerce-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
  frontend:
    build: frontend/.
    container_name: ecommerce-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
